# Site settings
title:       "If credit's what matters, I'll take credit."
email:       nick@dischord.org
author:      Nick Jones
description: "If credit's what matters, I'll take credit."
baseurl:     "/blog"
url:         "http://dischord.org"
paginate: 5

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: yankcrime
stackoverflow_id:
twitter_username: yankcrime
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

flickr:
    api_key: 167cb17dcb886af997217243c8a6d1a3

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /:year/:month/:day/:title
sass:
  compressed: true
gems:
  - jekyll-sitemap
